# -*- coding: utf-8 -*-
"""cnn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQ8NJpNkEcVMFn2-vv1joDr5z2fOivkk
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import cifar100
import numpy as np
import matplotlib.pyplot as plt
import os


# Build Parallel CNN Model
def build_parallel_cnn(input_shape=(32, 32, 3), num_classes=100):
    """Build a CNN with parallel convolutional layers to capture features at different scales"""
    inputs = layers.Input(shape=input_shape)

    # Parallel Branch 1: Small kernels (3x3)
    branch1 = layers.Conv2D(32, (3, 3), padding='same', activation='relu', name='branch1_conv1')(inputs)
    branch1 = layers.Conv2D(32, (3, 3), padding='same', activation='relu', name='branch1_conv2')(branch1)

    # Parallel Branch 2: Medium kernels (5x5)
    branch2 = layers.Conv2D(32, (5, 5), padding='same', activation='relu', name='branch2_conv1')(inputs)
    branch2 = layers.Conv2D(32, (5, 5), padding='same', activation='relu', name='branch2_conv2')(branch2)

    # Parallel Branch 3: Large kernels (7x7)
    branch3 = layers.Conv2D(32, (7, 7), padding='same', activation='relu', name='branch3_conv1')(inputs)
    branch3 = layers.Conv2D(32, (7, 7), padding='same', activation='relu', name='branch3_conv2')(branch3)

    # Parallel Branch 4: Max pooling path
    branch4 = layers.MaxPooling2D((3, 3), strides=1, padding='same', name='branch4_pool')(inputs)
    branch4 = layers.Conv2D(32, (1, 1), padding='same', activation='relu', name='branch4_conv')(branch4)

    # Concatenate all branches
    concat = layers.Concatenate(name='concat_branches')([branch1, branch2, branch3, branch4])

    # Additional convolutional layers
    x = layers.Conv2D(128, (3, 3), padding='same', activation='relu')(concat)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Dropout(0.25)(x)

    x = layers.Conv2D(256, (3, 3), padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2))(x)
    x = layers.Dropout(0.25)(x)

    # Dense layers
    x = layers.Flatten()(x)
    x = layers.Dense(512, activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.5)(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.5)(x)

    # Output layer
    outputs = layers.Dense(num_classes, activation='softmax', name='output')(x)

    model = models.Model(inputs=inputs, outputs=outputs, name='Parallel_CNN_CIFAR100')
    return model


# Load and preprocess data
def load_data():
    """Load and preprocess CIFAR-100 dataset"""
    (x_train, y_train), (x_test, y_test) = cifar100.load_data(label_mode='fine')

    # Normalize pixel values
    x_train = x_train.astype('float32') / 255.0
    x_test = x_test.astype('float32') / 255.0

    # Convert labels to categorical
    y_train = keras.utils.to_categorical(y_train, 100)
    y_test = keras.utils.to_categorical(y_test, 100)

    return (x_train, y_train), (x_test, y_test)


# Visualize model architecture
def visualize_architecture(model):
    """Display model summary and plot architecture"""
    model.summary()
    keras.utils.plot_model(
        model,
        to_file='parallel_cnn_architecture.png',
        show_shapes=True,
        show_layer_names=True,
        rankdir='TB',
        expand_nested=True,
        dpi=96
    )
    print("\nModel architecture saved as 'parallel_cnn_architecture.png'")


# Train the model
def train_model(model, x_train, y_train, x_test, y_test, epochs=50, batch_size=128):
    """Train the parallel CNN model with GPU optimization"""
    print("\nTraining Configuration:")
    print(f"  Batch Size: {batch_size}")
    print(f"  Max Epochs: {epochs}")

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    callbacks = [
        keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1),
        keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-7, verbose=1),
        keras.callbacks.ModelCheckpoint('best_parallel_cnn_cifar100.h5', monitor='val_accuracy', save_best_only=True, verbose=1),
        keras.callbacks.TensorBoard(log_dir='./logs', histogram_freq=1, write_graph=True, update_freq='epoch')
    ]

    print("\nStarting training on GPU...")
    with tf.device('/GPU:0'):
        history = model.fit(
            x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            callbacks=callbacks,
            verbose=1
        )
    return history


# Visualize training history
def plot_training_history(history):
    """Plot training and validation accuracy/loss"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(history.history['accuracy'], label='Train Accuracy')
    ax1.plot(history.history['val_accuracy'], label='Val Accuracy')
    ax1.set_title('Model Accuracy', fontsize=14)
    ax1.set_xlabel('Epoch')
    ax1.set_ylabel('Accuracy')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(history.history['loss'], label='Train Loss')
    ax2.plot(history.history['val_loss'], label='Val Loss')
    ax2.set_title('Model Loss', fontsize=14)
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Loss')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('training_history.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("\nTraining history saved as 'training_history.png'")


# Evaluate model
def evaluate_model(model, x_test, y_test):
    """Evaluate model and show sample predictions"""
    test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
    print(f"\nTest Accuracy: {test_acc*100:.2f}%")
    print(f"Test Loss: {test_loss:.4f}")

    predictions = model.predict(x_test[:16])
    fig, axes = plt.subplots(4, 4, figsize=(12, 12))
    for i, ax in enumerate(axes.flat):
        ax.imshow(x_test[i])
        pred_label = np.argmax(predictions[i])
        true_label = np.argmax(y_test[i])
        color = 'green' if pred_label == true_label else 'red'
        ax.set_title(f'Pred: {pred_label}\nTrue: {true_label}', color=color, fontsize=10)
        ax.axis('off')

    plt.tight_layout()
    plt.savefig('predictions.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("\nSample predictions saved as 'predictions.png'")


# Main
if __name__ == "__main__":
    print("="*60)
    print("Parallel CNN Image Classification (CIFAR-100)")
    print("="*60)

    print("\n1. Loading CIFAR-100 dataset...")
    (x_train, y_train), (x_test, y_test) = load_data()
    print(f"Training samples: {len(x_train)}")
    print(f"Test samples: {len(x_test)}")

    print("\n2. Building Parallel CNN model...")
    model = build_parallel_cnn(input_shape=(32, 32, 3), num_classes=100)

    print("\n3. Model Architecture:")
    visualize_architecture(model)

    print("\n4. Training model on GPU...")
    history = train_model(model, x_train, y_train, x_test, y_test, epochs=50, batch_size=128)

    print("\n5. Plotting training history...")
    plot_training_history(history)

    print("\n6. Evaluating model...")
    evaluate_model(model, x_test, y_test)

    print("\n" + "="*60)
    print("Training completed successfully!")
    print("TensorBoard logs saved in './logs' directory")
    print("Run: tensorboard --logdir=./logs")
    print("="*60)
    model.save('parallel_cnn_cifar100.h5')
    print("\nModel saved as 'parallel_cnn_cifar100.h5'")